development:
  adapter: postgresql
  database: ccni
  pool: 5
  host: localhost
  encoding: utf8
  username: postgres
  password: pqr10145
  timeout: 500

production:
  adapter: postgresql
  database: ccni
  pool: 5
  host: ccni.cck1k1sag20f.us-east-1.rds.amazonaws.com
  encoding: utf8
  username: inzpiral
  password: Planeta2014
  timeout: 500
